Addressing crowdworker feedback [WIP]
allenai/natural-instructions pull request #760
Opened 2022-04-13 23:15 UTC by yeganehkordi

#759 
I didn't get this feedback:
```
 - [ ] task393_plausible_result_generation.json
    - regarding instructions: `Maybe including examples where each answer the "who, what, when, where and why"?
```
Is this suggesting changing the task?

2022-04-22 17:52 UTC, danyaljj commented
@yeganehkordi this is still WIP?

2022-04-22 23:43 UTC, yeganehkordi commented
Not anymore, addressing the feedback is done now.

2022-04-26 16:52 UTC, danyaljj commented
@Palipoor wondering if you can help review this PR?

2022-04-26 18:10 UTC, Palipoor commented
Hi! Sorry I didn't see this. Yes. Will do asap.

2022-04-26 19:01 UTC, Palipoor requested changes
They all look good to me.

2022-04-26 19:01 UTC, Palipoor commented on tasks/task1156_bard_analogical_reasoning_tools.json
> +            "explanation": "The given analogy relates actions to the tools used to perform them. A knife can be used to cut. To cut, a scissors can be used as well."
a scissors => a pair of scissors / scissors.

2022-04-26 19:01 UTC, Palipoor commented on tasks/task1409_dart_text_generation.json
> +        "This task is based on the idea of making statements about resources in expressions of the form [subject, predicate, object], known as triples. You are given triples, and your task is to gene
I think this is a simpler beginning for the definition:

`In this task, you are given triplets. Each triplet is of the form [subject, predicate, object]. Your task is to generate ...`

2022-04-26 19:11 UTC, yeganehkordi commented
Thanks! Updated.

2022-04-27 18:47 UTC, merged